version: "3.8"
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data:/data
    environment:
      - SQLITE3_DB=myDb.sqlite
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    depends_on:
      - db
